name: Coverage-check
on:
  - push
  - pull_request
jobs:
  coverage:
    needs: [ test ]
    name: coverage
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - run: make install
      - uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.COVERAGE_Z }}
        with:
          coverageCommand: make test-coverage
          debug: true
